### ISSUE TITLE
Upload a new release to puppet forge

### ISSUE THREAD

**Issue by gfa** [dphilpot/dphilpot-nullmailer#7]
Hi

thanks for your module, I'm currently using 0.0.4 from Github but it would be great to take it from puppet forge like other modules
please consider making a release in puppet forge

thanks!

**Comment by dphilpot** [comment]
Hi @gfa 

since i've stopped using puppet about 1 year ago i'm unable to maintain it anymore.
You are free to do with it whatever you want to do.

I've Update the Module on Puppet Forge could you please Test it as i have no good way to confirm everythings working fine with recent puppet versions.

**Comment by gfa** [comment]
Hi @dphilpot 

thanks for the update, 0.0.4 works fine on modern Debian (stretch) and Puppet (5 and 6)

**Comment by dphilpot** [comment]
Awsome 👍
